### ISSUE TITLE
Crash on Windows 10

### ISSUE THREAD

**Issue by Maerchensarg** [Christian-Nunnally/Diiagramr#1]
Hi. Thanks for Diiagramr, but somehow I can not start it. Installation works fine, but the EXE crashes on my PC (Windows 10 Pro, latest Patchlevel):

> Name der fehlerhaften Anwendung: Diiagramr.exe, Version: 0.12.0.0, Zeitstempel: 0x5cb54be4
> Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.17763.404, Zeitstempel: 0x3424aead
> Ausnahmecode: 0xe0434352
> Fehleroffset: 0x0011c6f2
> ID des fehlerhaften Prozesses: 0x1fa4
> Startzeit der fehlerhaften Anwendung: 0x01d4f74dc2e6a31a
> Pfad der fehlerhaften Anwendung: C:\Users\***\AppData\Local\Apps\2.0\LO8LJ70A.V4A\9LXEPBRB.E8C\diia..tion_0000000000000000_0000.000c_be9f1df762b12c31\Diiagramr.exe
> Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
> Berichtskennung: 42ef3ce5-f452-4d57-bb8b-b19371f3a6be
> Vollständiger Name des fehlerhaften Pakets: 
> Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

---

> Anwendung: Diiagramr.exe
> Frameworkversion: v4.0.30319
> Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
> Ausnahmeinformationen: System.Security.Principal.IdentityNotMappedException
>    bei System.Security.Principal.NTAccount.Translate(System.Security.Principal.IdentityReferenceCollection, System.Type, Boolean)
>    bei System.Security.Principal.NTAccount.Translate(System.Type)
>    bei System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(System.Security.AccessControl.AccessControlModification, System.Security.AccessControl.AccessRule, Boolean ByRef)
>    bei System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(System.Security.AccessControl.AccessRule)
>    bei DiiagramrAPI.Service.DirectoryService.CreateDirectory(System.String)
>    bei DiiagramrAPI.Service.PluginLoader..ctor(System.Func`1<DiiagramrAPI.Service.Interfaces.IProvideNodes>, System.Func`1<DiiagramrAPI.Service.Interfaces.IDirectoryService>)
>    bei DynamicClass.lambda_method(System.Runtime.CompilerServices.Closure, StyletIoC.Creation.IRegistrationContext)
>    bei StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.FuncRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.FuncRegistration..ctor(StyletIoC.Creation.IRegistration)
>    bei StyletIoC.Internal.Container.TryCreateFuncFactory(System.Type, System.String, StyletIoC.Internal.IRegistrationCollection ByRef)
>    bei StyletIoC.Internal.Container.StyletIoC.Creation.IRegistrationContext.CanResolve(System.Type, System.String)
>    bei StyletIoC.Internal.Creators.TypeCreator+<>c__DisplayClassd.<GetInstanceExpression>b__3(System.Reflection.ParameterInfo)
>    bei System.Linq.Enumerable.All[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
>    bei StyletIoC.Internal.Creators.TypeCreator+<>c__DisplayClassd.<GetInstanceExpression>b__2(System.Reflection.ConstructorInfo)
>    bei System.Linq.Enumerable+WhereArrayIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
>    bei System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
>    bei System.Linq.OrderedEnumerable`1+<GetEnumerator>d__1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
>    bei System.Linq.Enumerable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
>    bei StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Creators.TypeCreator+<>c__DisplayClassd.<GetInstanceExpression>b__8(System.Reflection.ParameterInfo)
>    bei System.Linq.Enumerable+WhereSelectArrayIterator`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
>    bei System.Collections.Generic.List`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
>    bei System.Dynamic.Utils.CollectionExtensions.ToReadOnly[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
>    bei System.Linq.Expressions.Expression.New(System.Reflection.ConstructorInfo, System.Collections.Generic.IEnumerable`1<System.Linq.Expressions.Expression>)
>    bei StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.FuncRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.FuncRegistration..ctor(StyletIoC.Creation.IRegistration)
>    bei StyletIoC.Internal.Container.TryCreateFuncFactory(System.Type, System.String, StyletIoC.Internal.IRegistrationCollection ByRef)
>    bei StyletIoC.Internal.Container.StyletIoC.Creation.IRegistrationContext.CanResolve(System.Type, System.String)
>    bei StyletIoC.Internal.Creators.TypeCreator+<>c__DisplayClassd.<GetInstanceExpression>b__3(System.Reflection.ParameterInfo)
>    bei System.Linq.Enumerable.All[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
>    bei StyletIoC.Internal.Creators.TypeCreator+<>c__DisplayClassd.<GetInstanceExpression>b__2(System.Reflection.ConstructorInfo)
>    bei System.Linq.Enumerable+WhereArrayIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
>    bei System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
>    bei System.Linq.OrderedEnumerable`1+<GetEnumerator>d__1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
>    bei System.Linq.Enumerable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
>    bei StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.SingletonRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.FuncRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.FuncRegistration..ctor(StyletIoC.Creation.IRegistration)
>    bei StyletIoC.Internal.Container.TryCreateFuncFactory(System.Type, System.String, StyletIoC.Internal.IRegistrationCollection ByRef)
>    bei StyletIoC.Internal.Container.StyletIoC.Creation.IRegistrationContext.CanResolve(System.Type, System.String)
>    bei StyletIoC.Internal.Creators.TypeCreator+<>c__DisplayClassd.<GetInstanceExpression>b__3(System.Reflection.ParameterInfo)
>    bei System.Linq.Enumerable.All[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Func`2<System.__Canon,Boolean>)
>    bei StyletIoC.Internal.Creators.TypeCreator+<>c__DisplayClassd.<GetInstanceExpression>b__2(System.Reflection.ConstructorInfo)
>    bei System.Linq.Enumerable+WhereArrayIterator`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
>    bei System.Linq.Buffer`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]..ctor(System.Collections.Generic.IEnumerable`1<System.__Canon>)
>    bei System.Linq.OrderedEnumerable`1+<GetEnumerator>d__1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].MoveNext()
>    bei System.Linq.Enumerable.FirstOrDefault[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>)
>    bei StyletIoC.Internal.Creators.TypeCreator.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.TransientRegistration.GetInstanceExpression(System.Linq.Expressions.ParameterExpression)
>    bei StyletIoC.Internal.Registrations.RegistrationBase.GetGeneratorInternal()
>    bei StyletIoC.Internal.Registrations.RegistrationBase.GetGenerator()
>    bei StyletIoC.Internal.Container.Get(System.RuntimeTypeHandle, System.String, System.Type)
>    bei StyletIoC.Internal.Container.Get[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.String)
>    bei Stylet.Bootstrapper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].get_RootViewModel()
>    bei Stylet.Bootstrapper`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Launch()
>    bei Stylet.BootstrapperBase.Start(System.String[])
>    bei Stylet.BootstrapperBase.<Setup>b__0(System.Object, System.Windows.StartupEventArgs)
>    bei System.Windows.Application.OnStartup(System.Windows.StartupEventArgs)
>    bei System.Windows.Application.<.ctor>b__1_0(System.Object)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
>    bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    bei MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    bei System.Windows.Threading.DispatcherOperation.Invoke()
>    bei System.Windows.Threading.Dispatcher.ProcessQueue()
>    bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    bei MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    bei System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    bei System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
>    bei System.Windows.Application.RunDispatcher(System.Object)
>    bei System.Windows.Application.RunInternal(System.Windows.Window)
>    bei System.Windows.Application.Run(System.Windows.Window)
>    bei Diiagramr.Application.App.Main()

**Comment by Christian-Nunnally** [comment]
Hello!  Sorry Its taken me a few days to get back to you, also sorry you're
having problems :( On the bright side, you're one of the first 5 people to
even install the application, so you're an extra super duper early adopter!

It looks like Diiagramr is crashing when it is creating the 'Plugins'
folder in the installation directory. There are two things you can try:

1. Run Diiagramr as administrator.

If that doesn't work or you do not want to run it  as administrator:

2. Find the directory where Diiagramr is installed. It is installed in some
obscure directory in your appdata folder (mine is:
'C:\Users\chris\AppData\Local\Apps\2.0\T7N91CCJ.4QY\8DA42G01.Q2R\diia..tion_0000000000000000_0000.000b_be9e1d3933ac4bf1')
and in that directory, create a new directory called "Plugins", and one
called "Projects" like so:

![image](https://user-images.githubusercontent.com/9011863/56474536-ca866280-6440-11e9-8856-df665b94e105.png)

Let me know how that goes. I'll try to publish an update soon so that
creating those directories doesn't require admin permissions.

Christian

**Comment by Maerchensarg** [comment]
Hi. No need to rush. Yay, now I feel great. ^^ I wanted to see what Visual Drop looks like with my FC project. I'm glad there are such projects like this one. Thank you for your work.

I tried both ways and I can tell you:

1. This hasn't changed anything, same behavior.

2. After creating both folders I was able to start the software. Unfortunately it crashes this time when installing the libraries (FC) with the following error.

> Name der fehlerhaften Anwendung: Diiagramr.exe, Version: 0.12.0.0, Zeitstempel: 0x5cb54be4
> Name des fehlerhaften Moduls: KERNELBASE.dll, Version: 10.0.17763.404, Zeitstempel: 0x3424aead
> Ausnahmecode: 0xe0434352
> Fehleroffset: 0x0011c6f2
> ID des fehlerhaften Prozesses: 0x2b10
> Startzeit der fehlerhaften Anwendung: 0x01d4f8e5444c98b4
> Pfad der fehlerhaften Anwendung: C:\Users\xxx\AppData\Local\Apps\2.0\LO8LJ70A.V4A\9LXEPBRB.E8C\diia..tion_0000000000000000_0000.000c_be9f1df762b12c31\Diiagramr.exe
> Pfad des fehlerhaften Moduls: C:\Windows\System32\KERNELBASE.dll
> Berichtskennung: fe092b47-f543-464c-b85e-8463e0b6ca49
> Vollständiger Name des fehlerhaften Pakets: 
> Anwendungs-ID, die relativ zum fehlerhaften Paket ist: 

---

> Anwendung: Diiagramr.exe
> Frameworkversion: v4.0.30319
> Beschreibung: Der Prozess wurde aufgrund einer unbehandelten Ausnahme beendet.
> Ausnahmeinformationen: System.Security.Principal.IdentityNotMappedException
>    bei System.Security.Principal.NTAccount.Translate(System.Security.Principal.IdentityReferenceCollection, System.Type, Boolean)
>    bei System.Security.Principal.NTAccount.Translate(System.Type)
>    bei System.Security.AccessControl.CommonObjectSecurity.ModifyAccess(System.Security.AccessControl.AccessControlModification, System.Security.AccessControl.AccessRule, Boolean ByRef)
>    bei System.Security.AccessControl.CommonObjectSecurity.AddAccessRule(System.Security.AccessControl.AccessRule)
>    bei DiiagramrAPI.Service.DirectoryService.CreateDirectory(System.String)
>    bei DiiagramrAPI.Service.LibraryManager.CreateTemporaryDirectory(System.String)
>    bei DiiagramrAPI.Service.LibraryManager+<InstallLatestVersionOfLibraryAsync>d__21.MoveNext()
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>    bei DiiagramrAPI.Shell.Tools.LibraryManagerWindowViewModel+<InstallLibraryFromListItemAsync>d__22.MoveNext()
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
>    bei DiiagramrAPI.Shell.Tools.LibraryManagerWindowViewModel+<InstallPressed>d__16.MoveNext()
>    bei System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    bei System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    bei System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
>    bei MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
>    bei System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
>    bei System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
>    bei MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
>    bei System.Windows.Threading.DispatcherOperation.Invoke()
>    bei System.Windows.Threading.Dispatcher.ProcessQueue()
>    bei System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    bei MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
>    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
>    bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
>    bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
>    bei MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
>    bei System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
>    bei System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
>    bei System.Windows.Application.RunDispatcher(System.Object)
>    bei System.Windows.Application.RunInternal(System.Windows.Window)
>    bei System.Windows.Application.Run(System.Windows.Window)
>    bei Diiagramr.Application.App.Main()
